added the new build scripts for cmaker

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,125 @@
-# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
-
-language: R
+# cmaker Build
+language: r
 sudo: false
 cache: packages
 warnings_are_errors: true
+use_bioc: true
+bioc_required: true
+cran: http://cran.rstudio.com
+
+os:
+  - linux
+  - osx
+
+r:
+  - oldrel  
+  - release
+  - devel
+
+matrix: 
+  allow_failures:
+    - r: devel
+
+latex: false
+compiler: clang
+osx_image: xcode9
+
+env:
+  global:
+  - R_BUILD_ARGS=" --no-build-vignettes --no-manual"
+  - R_CHECK_ARGS=" --timings --as-cran --no-manual --install-args=--build"
+  - RGL_USE_NULL=TRUE
+  - WARNINGS_ARE_ERRORS=1 
+  - DISPLAY=:99.0
+
+before_install:
+  - ulimit -n 2048  
+  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
+  - export PROJ_DIR=`basename $PWD`
+  - fname=travis_helpers.sh
+  - wget -O ${fname} http://bit.ly/travis_helpers
+  - cat ${fname}; source ${fname}; rm ${fname}  
+  - export rver=`r_version`;
+  - export gh_user=`get_gh_user` ; echo $gh_user ;
+  - cat DESCRIPTION  
+  - export PACKAGE_NAME=`package_name`
+  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck  
+  # does all the clang exports  
+  - x=`export_clang_cxx`; eval ${x}
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      no_open_mp ; 
+    fi  
+  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
+  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
+  - clang_cxx  
+  - ./cleanup      
+  - echo $PATH ;
+  - Rscript -e "install.packages('Rcpp', type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"    
+  - install_deps_no_suggests
+
+script:
+  - x=`export_clang_cxx`; eval ${x}
+  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+  - rm -f travis_wait*.log
+  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)  
+  - ls
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+  - rm -f travis_wait*.log
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed"; 
+      check_fail; 
+      dump_logs; 
+      check_warnings ;      
+      travis_terminate 1;
+    fi
+  - ls
+  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
+  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
+  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
+      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
+    fi
+  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;      
+  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}
+  - if [[ "${gh_user}" == "stnava" ]]; then 
+      export secure_key=Y+JfKm3oXRUxpxyWjBtXimuBcuv3+D5iakzCwMJLqEDPjd+w9ow1x5a4GN/LfFg8Lbhflc8Uaz2bpxRuD5enk+RRmFtcXBB/IsnxkXBEM3fA2eT4ZIxq/aTt4HisOdXclyZc5PxAXFOVO8/QWcjh3boqSpOjscS0kYCWkm4KT9M= ;
+    elif [[ "${gh_user}" == "muschellij2" ]]; then 
+      export secure_key=GEm6au7Z/KYE880stogn3I0lbvAgzbX/wjX1eOAI60iDeyGcaLQncrc32ERmdOhArka3hzvTId+llRh6zQcSjF29GvFjJda5u0j9ZIYLWN7PvsZyoi56CjXkpfa7UrriON8WulpAsZhavANCOSkSg3uNyZ0LqXL+3bXFuz78VKgnpoJm+raWKHxq/DGtLGlRJZC9/hZFM9njzpDI+Av7KcKStWN9qtut/iqZptV1ZuZuMlr8PbD5fPthFxSmz2DpJlUYpy0tc5AJfXvWnPcSxVz40qW5ekVKcajOTr3CFO1fMz7CV4nrCwVYCQiZHCkOgOQQqX692XsT9iSNVYCY3E+2Szwu4mQtQ4bp1eOy18Z9WHhk0OQcTcOxHtNV77/wwDvSyuEnirpfqxsgMrrFh8CmtwDs/oLp2Na6QCdjcQ/bZofVtyxwPtdfjSFR8zs9B8jkEMJW7xWW2Xv8SroPD28exTOlql4nysC3n/yE1cOCs2+tf0drD+9Zzb1Qnxm5Z3DBteevttwgcLkSsoDxLDiGFQWb4RO9JY+386ahG8yDl7VqFK67BaZ1qrLsllHWnm2vGlXPjyDOiyIW4CeklwLgzUu0zXdPhUvqsgTzbPsMCXLwOV4Gfa/pFB6f+M0VaiZpSYcE4dGoSNuo2zmYLHA+thYjUwnjf91sNMx4PlU= ;
+    fi    
+
+
+after_failure:
+  - dump_logs
+
+after_success:
+  - dump_logs
+
+notifications:
+  email:
+    recipients:
+    - muschellij2@gmail.com
+    - stnava@gmail.com
+    on_success: change
+    on_failure: always
+
+# so no overwrite of linux build
+before_deploy:
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      rm -f *.tar.gz;
+    fi
+
+deploy:
+  provider: releases
+  api_key:
+    secure: ${secure_key}
+  file: ${PKG_FILE_NAME}
+  skip_cleanup: true
+  on:
+    tags: true
+    repo: ${gh_user}/${PROJ_DIR}
+    all_branches: true
+
+
